# Python Basic Programming Assignment 8

### 1. Write a Python Program to Add Two Matrices?

In [2]:
import numpy as np
X = [[13,8,4],
    [5,6,7],
    [8,9,10]]

Y = [[6,9,2],
    [7,8,4],
    [5,6,9]]

arr1= np.array(X)+np.array(Y)
print("Add two matrics :\n",arr1)


Add two matrics :
 [[19 17  6]
 [12 14 11]
 [13 15 19]]


### 2. Write a Python Program to Multiply Two Matrices?

In [3]:
arr1= np.array(X)*np.array(Y)
print("Mulitply two matrics :\n",arr1)

Mulitply two matrics :
 [[78 72  8]
 [35 48 28]
 [40 54 90]]


### 3. Write a Python Program to Transpose a Matrix?

In [4]:
print("original matrics :\n",np.array(X))
print("Transpose matrics :\n",np.array(X).T)

original matrics :
 [[13  8  4]
 [ 5  6  7]
 [ 8  9 10]]
Transpose matrics :
 [[13  5  8]
 [ 8  6  9]
 [ 4  7 10]]


### 4. Write a Python Program to Sort Words in Alphabetic Order?

In [5]:
text="Write a Python Program to Sort Words in Alphabetic Order"
print("Sorted Text :\n"," ".join(sorted(text.lower().split())))

Sorted Text :
 a alphabetic in order program python sort to words write


### 5.Write a Python Program to Remove Punctuation From a String?

In [1]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
my_str = input("Enter a string with punctuations :\n ")
print("\nEntered string is :\n ",my_str)
no_punct = ""
for char in my_str:
    if char not in punctuations:
        no_punct = no_punct + char
print("\nAfter removing punctuations, the string is : \n",no_punct)


Entered string is :
  He come @ palanpur. I will meet @ Bus stop. # Meet-up.

After removing punctuations, the string is : 
 He come  palanpur I will meet  Bus stop  Meetup
